version: colorful-192x108-16bit-v14palette
palette:
    - note: The most common color to appear at the bottom of the wallpaper.
      value: '#cccc11'
      count: 19361
    - note: The color farthest from the primary color.
      value: '#000000'
averageColor: '#cbcc12'
lightestColor: '#ffffcc'
darkestColor: '#889900'
mostFrequentColors:
    - value: '#cccc11'
      count: 19255
    - value: '#ffffbb'
      count: 27
mostSatulightedColors:
    - value: '#eeff77'
      count: 1
mostGroupedColors:
    - value: '#cccc11'
      count: 19150
bottomHalf:
    averageColor: '#cbcb12'
    lightestColor: '#ffffcc'
    darkestColor: '#889900'
    mostFrequentColors:
        - value: '#cccc11'
          count: 19361
        - value: '#ffffbb'
          count: 17
    mostSatulightedColors:
        - value: '#eedd77'
          count: 2
    mostGroupedColors:
        - value: '#cccc11'
          count: 19257
bottomThird:
    averageColor: '#cccc11'
    lightestColor: '#eeff99'
    darkestColor: '#888800'
    mostFrequentColors:
        - value: '#cccc11'
          count: 20405
    mostSatulightedColors:
        - value: '#ddee77'
          count: 1
    mostGroupedColors:
        - value: '#cccc11'
          count: 20403
bottomLine:
    averageColor: '#cccc11'
    lightestColor: '#cccc33'
    darkestColor: '#cccc11'
    mostFrequentColors:
        - value: '#cccc11'
          count: 20628
    mostSatulightedColors:
        - value: '#cccc33'
          count: 108
    mostGroupedColors:
        - value: '#cccc11'
          count: 20520
