version: colorful-192x108-16bit-v14palette
palette:
    - note: The most common color to appear at the bottom of the wallpaper.
      value: '#77aa88'
      count: 19116
    - note: The color farthest from the primary color.
      value: '#000000'
paletteCandidates:
    - note: 1st most satulighted color of the bottom half of the wallpaper
      value: '#77bb88'
      count: 2
    - note: 2nd most satulighted color of the bottom half of the wallpaper
      value: '#88bb77'
      count: 1
    - note: 1st most grouped color of the bottom half of the wallpaper
      value: '#77aa88'
      count: 19113
    - note: 1st most frequent color of the bottom half of the wallpaper
      value: '#77aa88'
      count: 19116
    - note: 2nd most frequent color of the bottom half of the wallpaper
      value: '#ddeedd'
      count: 169
    - note: The darkest color of the bottom half of the wallpaper
      value: '#559944'
    - note: The lightest color of the bottom half of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom third of the wallpaper
      value: '#99ccaa'
      count: 8
    - note: 2nd most satulighted color of the bottom third of the wallpaper
      value: '#bbddaa'
      count: 1
    - note: 1st most grouped color of the bottom third of the wallpaper
      value: '#77aa88'
      count: 20477
    - note: 1st most frequent color of the bottom third of the wallpaper
      value: '#77aa88'
      count: 20477
    - note: 2nd most frequent color of the bottom third of the wallpaper
      value: '#ffffff'
      count: 71
    - note: The darkest color of the bottom third of the wallpaper
      value: '#77aa77'
    - note: The lightest color of the bottom third of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the whole wallpaper
      value: '#77bb88'
      count: 4
    - note: 2nd most satulighted color of the whole wallpaper
      value: '#88bb77'
      count: 3
    - note: 1st most grouped color of the whole wallpaper
      value: '#77aa88'
      count: 18913
    - note: 1st most frequent color of the whole wallpaper
      value: '#77aa88'
      count: 18918
    - note: 2nd most frequent color of the whole wallpaper
      value: '#ddeedd'
      count: 202
    - note: The darkest color of the whole wallpaper
      value: '#559944'
    - note: The lightest color of the whole wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom line of the wallpaper
      value: '#77aa88'
      count: 20736
    - note: 1st most grouped color of the bottom line of the wallpaper
      value: '#77aa88'
      count: 20736
    - note: 1st most frequent color of the bottom line of the wallpaper
      value: '#77aa88'
      count: 20736
    - note: The darkest color of the bottom line of the wallpaper
      value: '#77aa88'
    - note: The lightest color of the bottom line of the wallpaper
      value: '#77aa88'
averageColor: '#7cad8c'
lightestColor: '#ffffff'
darkestColor: '#559944'
mostFrequentColors:
    - value: '#77aa88'
      count: 18918
    - value: '#ddeedd'
      count: 202
mostSatulightedColors:
    - value: '#77bb88'
      count: 4
    - value: '#88bb77'
      count: 3
mostGroupedColors:
    - value: '#77aa88'
      count: 18913
bottomHalf:
    averageColor: '#7cad8c'
    lightestColor: '#ffffff'
    darkestColor: '#559944'
    mostFrequentColors:
        - value: '#77aa88'
          count: 19116
        - value: '#ddeedd'
          count: 169
    mostSatulightedColors:
        - value: '#77bb88'
          count: 2
        - value: '#88bb77'
          count: 1
    mostGroupedColors:
        - value: '#77aa88'
          count: 19113
bottomThird:
    averageColor: '#78ab89'
    lightestColor: '#ffffff'
    darkestColor: '#77aa77'
    mostFrequentColors:
        - value: '#77aa88'
          count: 20477
        - value: '#ffffff'
          count: 71
    mostSatulightedColors:
        - value: '#99ccaa'
          count: 8
        - value: '#bbddaa'
          count: 1
    mostGroupedColors:
        - value: '#77aa88'
          count: 20477
bottomLine:
    averageColor: '#77aa88'
    lightestColor: '#77aa88'
    darkestColor: '#77aa88'
    mostFrequentColors:
        - value: '#77aa88'
          count: 20736
    mostSatulightedColors:
        - value: '#77aa88'
          count: 20736
    mostGroupedColors:
        - value: '#77aa88'
          count: 20736
