version: colorful-192x108-16bit-v12palette
palette:
    - '#66ccbb'
    - '#000000'
averageColor: '#6dccb8'
lightestColor: '#ffffff'
darkestColor: '#66aa55'
mostFrequentColors:
    - '#66ccbb'
    - '#ffffff'
mostSatulightedColors:
    - '#55ccbb'
    - '#66bb77'
    - '#77bb55'
mostGroupedColors:
    - '#66ccbb'
bottomHalf:
    averageColor: '#6ccbb8'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    mostFrequentColors:
        - '#66ccbb'
        - '#ffffff'
    mostSatulightedColors:
        - '#55ccbb'
        - '#cceeaa'
    mostGroupedColors:
        - '#66ccbb'
bottomThird:
    averageColor: '#66caba'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    mostFrequentColors:
        - '#66ccbb'
        - '#ffffff'
    mostSatulightedColors:
        - '#66cccc'
        - '#559977'
        - '#77aa55'
    mostGroupedColors:
        - '#66ccbb'
bottomLine:
    averageColor: '#66ccbb'
    lightestColor: '#77ccbb'
    darkestColor: '#66ccbb'
    mostFrequentColors:
        - '#66ccbb'
    mostSatulightedColors:
        - '#66ccbb'
    mostGroupedColors:
        - '#66ccbb'
