version: colorful-192x108-16bit-v12palette
palette:
    - '#77aa88'
    - '#000000'
averageColor: '#7cad8c'
lightestColor: '#ffffff'
darkestColor: '#559944'
mostFrequentColors:
    - '#77aa88'
    - '#ddeedd'
mostSatulightedColors:
    - '#77bb88'
    - '#88bb77'
mostGroupedColors:
    - '#77aa88'
bottomHalf:
    averageColor: '#7cad8c'
    lightestColor: '#ffffff'
    darkestColor: '#559944'
    mostFrequentColors:
        - '#77aa88'
        - '#ddeedd'
    mostSatulightedColors:
        - '#77bb88'
        - '#88bb77'
    mostGroupedColors:
        - '#77aa88'
bottomThird:
    averageColor: '#78ab89'
    lightestColor: '#ffffff'
    darkestColor: '#77aa77'
    mostFrequentColors:
        - '#77aa88'
        - '#ffffff'
    mostSatulightedColors:
        - '#99ccaa'
        - '#bbddaa'
    mostGroupedColors:
        - '#77aa88'
bottomLine:
    averageColor: '#77aa88'
    lightestColor: '#77aa88'
    darkestColor: '#77aa88'
    mostFrequentColors:
        - '#77aa88'
    mostSatulightedColors:
        - '#77aa88'
    mostGroupedColors:
        - '#77aa88'
