version: colorful-192x108-16bit-v13palette
palette:
    - note: Most frequent color
      value: '#77aa88'
      count: 19116
    - note: Most distant color from primary color
      value: '#000000'
averageColor: '#7cad8c'
lightestColor: '#ffffff'
darkestColor: '#559944'
mostFrequentColors:
    - value: '#77aa88'
      count: 18918
    - value: '#ddeedd'
      count: 202
mostSatulightedColors:
    - value: '#77bb88'
      count: 4
    - value: '#88bb77'
      count: 3
mostGroupedColors:
    - value: '#77aa88'
      count: 18913
bottomHalf:
    averageColor: '#7cad8c'
    lightestColor: '#ffffff'
    darkestColor: '#559944'
    mostFrequentColors:
        - value: '#77aa88'
          count: 19116
        - value: '#ddeedd'
          count: 169
    mostSatulightedColors:
        - value: '#77bb88'
          count: 2
        - value: '#88bb77'
          count: 1
    mostGroupedColors:
        - value: '#77aa88'
          count: 19113
bottomThird:
    averageColor: '#78ab89'
    lightestColor: '#ffffff'
    darkestColor: '#77aa77'
    mostFrequentColors:
        - value: '#77aa88'
          count: 20477
        - value: '#ffffff'
          count: 71
    mostSatulightedColors:
        - value: '#99ccaa'
          count: 8
        - value: '#bbddaa'
          count: 1
    mostGroupedColors:
        - value: '#77aa88'
          count: 20477
bottomLine:
    averageColor: '#77aa88'
    lightestColor: '#77aa88'
    darkestColor: '#77aa88'
    mostFrequentColors:
        - value: '#77aa88'
          count: 20736
    mostSatulightedColors:
        - value: '#77aa88'
          count: 20736
    mostGroupedColors:
        - value: '#77aa88'
          count: 20736
