version: colorful-192x108-16bit-v14palette
palette:
    - note: The most common color to appear at the bottom of the wallpaper.
      value: '#cccc11'
      count: 19361
    - note: The color farthest from the primary color.
      value: '#000000'
paletteCandidates:
    - note: 1st most satulighted color of the bottom half of the wallpaper
      value: '#eedd77'
      count: 2
    - note: 1st most grouped color of the bottom half of the wallpaper
      value: '#cccc11'
      count: 19257
    - note: 1st most frequent color of the bottom half of the wallpaper
      value: '#cccc11'
      count: 19361
    - note: 2nd most frequent color of the bottom half of the wallpaper
      value: '#ffffbb'
      count: 17
    - note: The darkest color of the bottom half of the wallpaper
      value: '#889900'
    - note: The lightest color of the bottom half of the wallpaper
      value: '#ffffcc'
    - note: 1st most satulighted color of the bottom third of the wallpaper
      value: '#ddee77'
      count: 1
    - note: 1st most grouped color of the bottom third of the wallpaper
      value: '#cccc11'
      count: 20403
    - note: 1st most frequent color of the bottom third of the wallpaper
      value: '#cccc11'
      count: 20405
    - note: The darkest color of the bottom third of the wallpaper
      value: '#888800'
    - note: The lightest color of the bottom third of the wallpaper
      value: '#eeff99'
    - note: 1st most satulighted color of the whole wallpaper
      value: '#eeff77'
      count: 1
    - note: 1st most grouped color of the whole wallpaper
      value: '#cccc11'
      count: 19150
    - note: 1st most frequent color of the whole wallpaper
      value: '#cccc11'
      count: 19255
    - note: 2nd most frequent color of the whole wallpaper
      value: '#ffffbb'
      count: 27
    - note: The darkest color of the whole wallpaper
      value: '#889900'
    - note: The lightest color of the whole wallpaper
      value: '#ffffcc'
    - note: 1st most satulighted color of the bottom line of the wallpaper
      value: '#cccc33'
      count: 108
    - note: 1st most grouped color of the bottom line of the wallpaper
      value: '#cccc11'
      count: 20520
    - note: 1st most frequent color of the bottom line of the wallpaper
      value: '#cccc11'
      count: 20628
    - note: The darkest color of the bottom line of the wallpaper
      value: '#cccc11'
    - note: The lightest color of the bottom line of the wallpaper
      value: '#cccc33'
averageColor: '#cbcc12'
lightestColor: '#ffffcc'
darkestColor: '#889900'
mostFrequentColors:
    - value: '#cccc11'
      count: 19255
    - value: '#ffffbb'
      count: 27
mostSatulightedColors:
    - value: '#eeff77'
      count: 1
mostGroupedColors:
    - value: '#cccc11'
      count: 19150
bottomHalf:
    averageColor: '#cbcb12'
    lightestColor: '#ffffcc'
    darkestColor: '#889900'
    mostFrequentColors:
        - value: '#cccc11'
          count: 19361
        - value: '#ffffbb'
          count: 17
    mostSatulightedColors:
        - value: '#eedd77'
          count: 2
    mostGroupedColors:
        - value: '#cccc11'
          count: 19257
bottomThird:
    averageColor: '#cccc11'
    lightestColor: '#eeff99'
    darkestColor: '#888800'
    mostFrequentColors:
        - value: '#cccc11'
          count: 20405
    mostSatulightedColors:
        - value: '#ddee77'
          count: 1
    mostGroupedColors:
        - value: '#cccc11'
          count: 20403
bottomLine:
    averageColor: '#cccc11'
    lightestColor: '#cccc33'
    darkestColor: '#cccc11'
    mostFrequentColors:
        - value: '#cccc11'
          count: 20628
    mostSatulightedColors:
        - value: '#cccc33'
          count: 108
    mostGroupedColors:
        - value: '#cccc11'
          count: 20520
