version: colorful-1920x1080-256bit-v14palette
palette:
    - note: 1st most frequent color of the whole wallpaper that is the most similar
          color to the average color of the bottom third of the wallpaper.
      value: '#c0951d'
      count: 1549285
    - note: The color farthest from the primary color.
      value: '#000000'
    - note: The lightest color of the bottom third of the wallpaper which is distant
          enough (10%) and hue-distant enough (30°) from all other palette
          colors.
      value: '#fbfcfa'
averageColor: '#bf9724'
lightestColor: '#fffefc'
darkestColor: '#202b07'
mostFrequentColors:
    - value: '#c0951d'
      count: 1549285
    - value: '#f6ebad'
      count: 7002
    - value: '#394827'
      count: 1820
mostSatulightedColors:
    - value: '#edda77'
      count: 4
mostGroupedColors:
    - value: '#c0951d'
      count: 1538138
bottomHalf:
    averageColor: '#bd9522'
    lightestColor: '#fffefc'
    darkestColor: '#444400'
    mostFrequentColors:
        - value: '#c0951d'
          count: 1579915
        - value: '#f6ebad'
          count: 4875
        - value: '#394727'
          count: 1899
    mostSatulightedColors:
        - value: '#d9bd5f'
          count: 2
    mostGroupedColors:
        - value: '#c0951d'
          count: 1560972
bottomThird:
    averageColor: '#bf951e'
    lightestColor: '#fbfcfa'
    darkestColor: '#444400'
    mostFrequentColors:
        - value: '#c0951d'
          count: 1642675
        - value: '#394727'
          count: 644
        - value: '#f6f3f1'
          count: 66
    mostSatulightedColors:
        - value: '#d9bd5f'
          count: 4
    mostGroupedColors:
        - value: '#c0951d'
          count: 1631411
bottomLine:
    averageColor: '#c0961a'
    lightestColor: '#bc932a'
    darkestColor: '#c09619'
    mostFrequentColors:
        - value: '#c0961a'
          count: 1890000
    mostSatulightedColors:
        - value: '#bf9329'
          count: 2160
    mostGroupedColors:
        - value: '#c0961a'
          count: 1433160
