version: 5
averageColor: '#cbcc12'
lightestColor: '#ffffdd'
darkestColor: '#889900'
minmaxWhite:
    - '#ffffdd'
    - '#888800'
minmaxRed:
    - '#888800'
    - '#ffffdd'
minmaxGreen:
    - '#88aa11'
    - '#ffeedd'
minmaxBlue:
    - '#99aa44'
    - '#eeff44'
mostFrequentColors:
    - '#cccc33'
mostSatulightedColors:
    - '#ffff77'
    - '#eeff66'
    - '#eeff55'
    - '#eeff77'
    - '#eeff44'
    - '#eeee55'
    - '#ffff88'
    - '#eeee66'
    - '#eeee44'
    - '#ddff44'
    - '#eeff88'
    - '#ddee55'
    - '#ddee66'
    - '#eedd77'
    - '#eeee77'
    - '#ddee44'
    - '#ddee77'
    - '#dddd55'
    - '#ddcc55'
    - '#ffff99'
    - '#ffee99'
    - '#dddd44'
    - '#ccee44'
    - '#dddd66'
    - '#ddcc66'
    - '#ddee33'
    - '#eeff99'
    - '#ccdd55'
    - '#eeee88'
    - '#eedd88'
    - '#ccdd44'
    - '#dddd33'
    - '#ccdd66'
    - '#ddee88'
    - '#bbdd55'
    - '#ccee33'
    - '#dddd77'
    - '#bbdd66'
    - '#cccc44'
    - '#ccbb44'
    - '#bbdd44'
    - '#cccc55'
    - '#ccbb55'
    - '#ccdd33'
    - '#ccdd77'
    - '#ddee22'
    - '#ffffaa'
    - '#ffeeaa'
    - '#cccc33'
    - '#ccbb33'
    - '#dddd22'
    - '#bbcc55'
    - '#bbcc44'
    - '#cccc66'
    - '#eeffaa'
    - '#bbdd33'
    - '#eeee99'
    - '#eedd99'
    - '#ddffaa'
    - '#aacc55'
    - '#ccee22'
    - '#bbcc66'
    - '#bbcc33'
    - '#ddee99'
    - '#aacc44'
    - '#bbbb44'
    - '#ccdd22'
    - '#dddd88'
    - '#cccc22'
    - '#ccbb22'
    - '#bbbb55'
    - '#bbbb33'
    - '#bbaa33'
    - '#aacc33'
    - '#cccc77'
    - '#aabb44'
    - '#bbdd22'
    - '#aabb55'
    - '#bbcc77'
    - '#aabb33'
    - '#bbcc22'
    - '#99bb44'
    - '#bbbb66'
    - '#bbbb22'
    - '#bbaa22'
    - '#aaaa44'
    - '#ffffbb'
    - '#ffeebb'
    - '#aaaa33'
    - '#99bb33'
    - '#eeffbb'
    - '#eeeeaa'
    - '#aacc22'
    - '#ccdd11'
    - '#cccc11'
    - '#ccbb11'
    - '#ddeeaa'
    - '#99aa44'
    - '#dddd99'
    - '#aabb22'
    - '#99aa33'
    - '#ccdd99'
    - '#aaaa22'
    - '#cccc88'
    - '#bbdd11'
    - '#bbcc88'
    - '#bbcc11'
    - '#99bb22'
    - '#bbbb11'
    - '#bbaa11'
    - '#99aa22'
    - '#aacc11'
    - '#aabb11'
    - '#aaaa11'
    - '#aa9911'
    - '#cccc00'
    - '#ffffcc'
    - '#eeeebb'
    - '#eeffcc'
    - '#99bb11'
    - '#ddddaa'
    - '#99aa11'
    - '#cccc99'
    - '#999911'
    - '#bbbb00'
    - '#bbcc00'
    - '#bbaa00'
    - '#88aa11'
    - '#888811'
    - '#aabb00'
    - '#aaaa00'
    - '#aacc00'
    - '#99aa00'
    - '#999900'
    - '#99bb00'
    - '#ffffdd'
    - '#ffeedd'
    - '#eeeecc'
    - '#889900'
    - '#888800'
mostGroupedColors:
    - '#cccc11'
bottomHalf:
    averageColor: '#cbcb11'
    lightestColor: '#ffffdd'
    darkestColor: '#889900'
    minmaxWhite:
        - '#ffffdd'
        - '#888800'
    minmaxRed:
        - '#888800'
        - '#ffffdd'
    minmaxGreen:
        - '#88aa11'
        - '#ffffdd'
    minmaxBlue:
        - '#99aa44'
        - '#ffff77'
    mostFrequentColors:
        - '#cccc33'
    mostSatulightedColors:
        - '#ffff77'
        - '#eeee55'
        - '#ffff88'
        - '#eeee66'
        - '#eeff88'
        - '#ddee66'
        - '#eedd77'
        - '#eeee77'
        - '#ddee77'
        - '#dddd55'
        - '#ddcc55'
        - '#ffff99'
        - '#ffee99'
        - '#dddd44'
        - '#dddd66'
        - '#ddcc66'
        - '#ddee33'
        - '#eeff99'
        - '#ccdd55'
        - '#eeee88'
        - '#eedd88'
        - '#ccdd44'
        - '#dddd33'
        - '#ccdd66'
        - '#ddee88'
        - '#bbdd55'
        - '#dddd77'
        - '#bbdd66'
        - '#cccc44'
        - '#ccbb44'
        - '#bbdd44'
        - '#cccc55'
        - '#ccbb55'
        - '#ccdd33'
        - '#ccdd77'
        - '#ffffaa'
        - '#ffeeaa'
        - '#cccc33'
        - '#ccbb33'
        - '#dddd22'
        - '#bbcc55'
        - '#bbcc44'
        - '#cccc66'
        - '#eeffaa'
        - '#bbdd33'
        - '#eeee99'
        - '#ddffaa'
        - '#aacc55'
        - '#bbcc66'
        - '#bbcc33'
        - '#ddee99'
        - '#aacc44'
        - '#bbbb44'
        - '#ccdd22'
        - '#dddd88'
        - '#cccc22'
        - '#ccbb22'
        - '#bbbb55'
        - '#bbbb33'
        - '#bbaa33'
        - '#aacc33'
        - '#cccc77'
        - '#aabb44'
        - '#bbdd22'
        - '#aabb55'
        - '#bbcc77'
        - '#aabb33'
        - '#bbcc22'
        - '#99bb44'
        - '#bbbb66'
        - '#bbbb22'
        - '#bbaa22'
        - '#aaaa44'
        - '#ffffbb'
        - '#aaaa33'
        - '#99bb33'
        - '#eeffbb'
        - '#eeeeaa'
        - '#aacc22'
        - '#ccdd11'
        - '#cccc11'
        - '#ccbb11'
        - '#ddeeaa'
        - '#99aa44'
        - '#dddd99'
        - '#aabb22'
        - '#99aa33'
        - '#ccdd99'
        - '#aaaa22'
        - '#cccc88'
        - '#bbdd11'
        - '#bbcc88'
        - '#bbcc11'
        - '#99bb22'
        - '#bbbb11'
        - '#bbaa11'
        - '#99aa22'
        - '#aacc11'
        - '#aabb11'
        - '#aaaa11'
        - '#aa9911'
        - '#cccc00'
        - '#ffffcc'
        - '#eeeebb'
        - '#eeffcc'
        - '#99bb11'
        - '#ddddaa'
        - '#99aa11'
        - '#cccc99'
        - '#999911'
        - '#bbbb00'
        - '#bbcc00'
        - '#bbaa00'
        - '#88aa11'
        - '#888811'
        - '#aabb00'
        - '#aaaa00'
        - '#aacc00'
        - '#99aa00'
        - '#999900'
        - '#99bb00'
        - '#ffffdd'
        - '#eeeecc'
        - '#889900'
        - '#888800'
    mostGroupedColors:
        - '#cccc11'
bottomThird:
    averageColor: '#cccc11'
    lightestColor: '#ffffcc'
    darkestColor: '#889900'
    minmaxWhite:
        - '#ffffcc'
        - '#888800'
    minmaxRed:
        - '#888800'
        - '#ffffcc'
    minmaxGreen:
        - '#aacc11'
        - '#ffffcc'
    minmaxBlue:
        - '#888800'
        - '#ffff77'
    mostFrequentColors:
        - '#cccc33'
    mostSatulightedColors:
        - '#ffff77'
        - '#eeee55'
        - '#ffff88'
        - '#eeee77'
        - '#ddee77'
        - '#ddcc55'
        - '#dddd55'
        - '#ffee99'
        - '#ffff99'
        - '#dddd44'
        - '#dddd66'
        - '#ddcc66'
        - '#eeff99'
        - '#ccdd55'
        - '#eeee88'
        - '#ccdd44'
        - '#dddd33'
        - '#ccdd66'
        - '#ddee88'
        - '#dddd77'
        - '#cccc44'
        - '#cccc55'
        - '#ffffaa'
        - '#cccc33'
        - '#bbcc55'
        - '#bbcc44'
        - '#cccc66'
        - '#eeffaa'
        - '#eeee99'
        - '#bbcc66'
        - '#bbcc33'
        - '#ccdd22'
        - '#cccc22'
        - '#bbbb55'
        - '#bbbb33'
        - '#bbcc22'
        - '#bbbb22'
        - '#ffffbb'
        - '#eeffbb'
        - '#ccdd11'
        - '#cccc11'
        - '#aabb22'
        - '#aaaa22'
        - '#bbcc11'
        - '#bbbb11'
        - '#aacc11'
        - '#aabb11'
        - '#aaaa11'
        - '#cccc00'
        - '#ffffcc'
        - '#eeeebb'
        - '#99aa11'
        - '#999911'
        - '#bbbb00'
        - '#bbcc00'
        - '#aaaa00'
        - '#aabb00'
        - '#99aa00'
        - '#999900'
        - '#889900'
        - '#888800'
    mostGroupedColors:
        - '#cccc11'
bottomLine:
    averageColor: '#cccc11'
    lightestColor: '#cccc33'
    darkestColor: '#cccc11'
    minmaxWhite:
        - '#cccc33'
        - '#cccc11'
    minmaxRed:
        - '#cccc11'
        - '#cccc33'
    minmaxGreen:
        - '#cccc11'
        - '#cccc33'
    minmaxBlue:
        - '#cccc33'
        - '#cccc11'
    mostFrequentColors:
        - '#cccc33'
    mostSatulightedColors:
        - '#cccc33'
        - '#cccc22'
        - '#cccc11'
    mostGroupedColors:
        - '#cccc11'
