version: colorful-192x108-16bit-v12palette
palette:
    - '#66bb99'
    - '#000000'
    - '#eeaa55'
averageColor: '#72bc99'
lightestColor: '#ffffff'
darkestColor: '#ee8833'
mostFrequentColors:
    - '#66bb99'
    - '#ffeecc'
    - '#ee9944'
mostSatulightedColors:
    - '#55bb99'
    - '#ee9955'
    - '#99aa66'
mostGroupedColors:
    - '#66bb99'
bottomHalf:
    averageColor: '#73bc99'
    lightestColor: '#ffffff'
    darkestColor: '#ee8833'
    mostFrequentColors:
        - '#66bb99'
        - '#ffeecc'
        - '#ee9944'
    mostSatulightedColors:
        - '#55bb99'
        - '#eeaa55'
        - '#99aa66'
    mostGroupedColors:
        - '#66bb99'
bottomThird:
    averageColor: '#6bbc99'
    lightestColor: '#ffffff'
    darkestColor: '#cc9944'
    mostFrequentColors:
        - '#66bb99'
        - '#ffeecc'
        - '#ee9944'
    mostSatulightedColors:
        - '#55bb99'
        - '#ee9944'
        - '#ffffcc'
    mostGroupedColors:
        - '#66bb99'
bottomLine:
    averageColor: '#66bb99'
    lightestColor: '#66bb99'
    darkestColor: '#55bb99'
    mostFrequentColors:
        - '#66bb99'
    mostSatulightedColors:
        - '#55bb99'
    mostGroupedColors:
        - '#66bb99'
