version: colorful-192x108-16bit-v12palette
palette:
    - '#335522'
    - '#ffffff'
    - '#eecc55'
averageColor: '#3c5a24'
lightestColor: '#eedd77'
darkestColor: '#333311'
mostFrequentColors:
    - '#335522'
    - '#eecc55'
mostSatulightedColors:
    - '#eecc55'
mostGroupedColors:
    - '#335522'
bottomHalf:
    averageColor: '#3c5a23'
    lightestColor: '#888877'
    darkestColor: '#555500'
    mostFrequentColors:
        - '#335522'
        - '#ddbb33'
    mostSatulightedColors:
        - '#eecc55'
    mostGroupedColors:
        - '#335522'
bottomThird:
    averageColor: '#355623'
    lightestColor: '#998877'
    darkestColor: '#333300'
    mostFrequentColors:
        - '#335522'
        - '#ddaa22'
    mostSatulightedColors:
        - '#eebb33'
    mostGroupedColors:
        - '#335522'
bottomLine:
    averageColor: '#335533'
    lightestColor: '#335533'
    darkestColor: '#335522'
    mostFrequentColors:
        - '#335533'
    mostSatulightedColors:
        - '#335522'
    mostGroupedColors:
        - '#335533'
