version: colorful-192x108-16bit-v12palette
palette:
    - '#bb9922'
    - '#000000'
averageColor: '#ba9a28'
lightestColor: '#ffffee'
darkestColor: '#665500'
mostFrequentColors:
    - '#bb9922'
    - '#eeeeaa'
    - '#334422'
mostSatulightedColors:
    - '#ffee99'
mostGroupedColors:
    - '#bb9922'
bottomHalf:
    averageColor: '#b89926'
    lightestColor: '#ffffff'
    darkestColor: '#444400'
    mostFrequentColors:
        - '#bb9922'
        - '#334422'
        - '#eeeeaa'
    mostSatulightedColors:
        - '#ffeeaa'
    mostGroupedColors:
        - '#bb9922'
bottomThird:
    averageColor: '#ba9922'
    lightestColor: '#ffffee'
    darkestColor: '#555500'
    mostFrequentColors:
        - '#bb9922'
        - '#334422'
        - '#ffeecc'
    mostSatulightedColors:
        - '#ddcc77'
    mostGroupedColors:
        - '#bb9922'
bottomLine:
    averageColor: '#bb9921'
    lightestColor: '#bb9922'
    darkestColor: '#bb9911'
    mostFrequentColors:
        - '#bb9922'
    mostSatulightedColors:
        - '#bb9922'
    mostGroupedColors:
        - '#bb9922'
