version: colorful-192x108-16bit-v12palette
palette:
    - '#eeeedd'
    - '#000000'
    - '#447755'
averageColor: '#e1e4d2'
lightestColor: '#ffffff'
darkestColor: '#335533'
mostFrequentColors:
    - '#eeeedd'
    - '#446644'
mostSatulightedColors:
    - '#447755'
    - '#eeffdd'
mostGroupedColors:
    - '#eeeedd'
bottomHalf:
    averageColor: '#e0e3d1'
    lightestColor: '#ffffff'
    darkestColor: '#335533'
    mostFrequentColors:
        - '#eeeedd'
        - '#446644'
    mostSatulightedColors:
        - '#447755'
        - '#eeffdd'
    mostGroupedColors:
        - '#eeeedd'
bottomThird:
    averageColor: '#e9ead9'
    lightestColor: '#ffffff'
    darkestColor: '#335533'
    mostFrequentColors:
        - '#eeeedd'
        - '#446644'
    mostSatulightedColors:
        - '#558866'
        - '#aabb99'
    mostGroupedColors:
        - '#eeeedd'
bottomLine:
    averageColor: '#eeeedd'
    lightestColor: '#eeeedd'
    darkestColor: '#eeeedd'
    mostFrequentColors:
        - '#eeeedd'
    mostSatulightedColors:
        - '#eeeedd'
    mostGroupedColors:
        - '#eeeedd'
