version: 5
averageColor: '#6dccb8'
lightestColor: '#ffffff'
darkestColor: '#66aa44'
minmaxWhite:
    - '#ffffff'
    - '#447777'
minmaxRed:
    - '#779944'
    - '#eeffff'
minmaxGreen:
    - '#66bb55'
    - '#ffffff'
minmaxBlue:
    - '#447788'
    - '#ffffdd'
mostFrequentColors:
    - '#77bbbb'
mostSatulightedColors:
    - '#55ccbb'
    - '#44bbaa'
    - '#66cccc'
    - '#66bbcc'
    - '#55bbbb'
    - '#55aabb'
    - '#44aaaa'
    - '#4499aa'
    - '#55ccaa'
    - '#339999'
    - '#338899'
    - '#66ccbb'
    - '#55bbaa'
    - '#44aa99'
    - '#66ccaa'
    - '#77cccc'
    - '#66bbbb'
    - '#66aabb'
    - '#55aaaa'
    - '#5599aa'
    - '#55bb99'
    - '#449999'
    - '#448899'
    - '#338888'
    - '#44aa88'
    - '#77ccbb'
    - '#66cc99'
    - '#66bbaa'
    - '#55aa99'
    - '#55bb88'
    - '#88ddbb'
    - '#449988'
    - '#77ccaa'
    - '#66bb99'
    - '#88cccc'
    - '#77bbbb'
    - '#55aa88'
    - '#66aaaa'
    - '#6699aa'
    - '#559999'
    - '#558899'
    - '#448888'
    - '#447788'
    - '#449977'
    - '#aaeedd'
    - '#99ddcc'
    - '#88ccbb'
    - '#66bb88'
    - '#77bbaa'
    - '#bbffdd'
    - '#66aa99'
    - '#aaeecc'
    - '#55aa77'
    - '#559988'
    - '#aadd88'
    - '#448877'
    - '#77bb99'
    - '#99cc77'
    - '#66bb77'
    - '#ddffbb'
    - '#66aa88'
    - '#88cc77'
    - '#cceeaa'
    - '#ccdd99'
    - '#77bb55'
    - '#559977'
    - '#88bb66'
    - '#bbdd99'
    - '#55aa66'
    - '#bbcc88'
    - '#aadddd'
    - '#66bb55'
    - '#99cccc'
    - '#99bbcc'
    - '#aadd99'
    - '#88bbbb'
    - '#88aabb'
    - '#77bb66'
    - '#88aa55'
    - '#77aaaa'
    - '#7799aa'
    - '#aacc88'
    - '#669999'
    - '#77aa44'
    - '#aabb77'
    - '#558888'
    - '#99cc88'
    - '#66bb66'
    - '#447777'
    - '#66aa77'
    - '#ccffee'
    - '#77aa55'
    - '#99bb77'
    - '#bbeedd'
    - '#aaddcc'
    - '#99aa66'
    - '#66aa44'
    - '#99ccbb'
    - '#88bb77'
    - '#88bbaa'
    - '#66aa55'
    - '#779944'
    - '#77aa99'
    - '#559966'
    - '#88aa66'
    - '#ccffdd'
    - '#77bb77'
    - '#bbeecc'
    - '#aaddbb'
    - '#77aa66'
    - '#eeffcc'
    - '#669944'
    - '#ddeebb'
    - '#ddffcc'
    - '#779955'
    - '#ccddaa'
    - '#cceebb'
    - '#66aa66'
    - '#ccffcc'
    - '#bbeebb'
    - '#bbddaa'
    - '#bbcc99'
    - '#669955'
    - '#aacc99'
    - '#aabb88'
    - '#669977'
    - '#99cc99'
    - '#99bb88'
    - '#99aa77'
    - '#559955'
    - '#88bb88'
    - '#88aa77'
    - '#889966'
    - '#77aa77'
    - '#779966'
    - '#669966'
    - '#cceeee'
    - '#bbdddd'
    - '#bbccdd'
    - '#aacccc'
    - '#aabbcc'
    - '#99bbbb'
    - '#99aabb'
    - '#88aaaa'
    - '#779999'
    - '#ddffee'
    - '#cceedd'
    - '#bbddcc'
    - '#ffffdd'
    - '#ffeedd'
    - '#eeeecc'
    - '#eeffdd'
    - '#ddddbb'
    - '#ddeecc'
    - '#ccccaa'
    - '#ddffdd'
    - '#ccddbb'
    - '#cceecc'
    - '#bbccaa'
    - '#bbddbb'
    - '#aabb99'
    - '#aaccaa'
    - '#99bb99'
    - '#889977'
    - '#88aa88'
    - '#eeffff'
    - '#ddeeee'
    - '#ccdddd'
    - '#ffffee'
    - '#ffeeee'
    - '#eeeedd'
    - '#ddddcc'
    - '#ccccbb'
    - '#eeffee'
    - '#ddeedd'
    - '#ccddcc'
    - '#eeeeee'
    - '#ffffff'
mostGroupedColors:
    - '#66ccbb'
bottomHalf:
    averageColor: '#6ccbb8'
    lightestColor: '#ffffff'
    darkestColor: '#66aa44'
    minmaxWhite:
        - '#ffffff'
        - '#447777'
    minmaxRed:
        - '#779944'
        - '#eeffff'
    minmaxGreen:
        - '#66bb55'
        - '#ffffff'
    minmaxBlue:
        - '#447788'
        - '#ffffdd'
    mostFrequentColors:
        - '#77bbbb'
    mostSatulightedColors:
        - '#55ccbb'
        - '#44bbaa'
        - '#66cccc'
        - '#55bbbb'
        - '#55aabb'
        - '#44aaaa'
        - '#4499aa'
        - '#339999'
        - '#338899'
        - '#66ccbb'
        - '#55bbaa'
        - '#44aa99'
        - '#66bbbb'
        - '#66aabb'
        - '#55aaaa'
        - '#5599aa'
        - '#55bb99'
        - '#449999'
        - '#448899'
        - '#338888'
        - '#44aa88'
        - '#77ccbb'
        - '#66bbaa'
        - '#55aa99'
        - '#449988'
        - '#66bb99'
        - '#77bbbb'
        - '#55aa88'
        - '#66aaaa'
        - '#6699aa'
        - '#559999'
        - '#558899'
        - '#448888'
        - '#447788'
        - '#449977'
        - '#99ddcc'
        - '#88ccbb'
        - '#66bb88'
        - '#77bbaa'
        - '#66aa99'
        - '#55aa77'
        - '#559988'
        - '#aadd88'
        - '#448877'
        - '#99cc77'
        - '#66bb77'
        - '#66aa88'
        - '#88cc77'
        - '#cceeaa'
        - '#ccdd99'
        - '#77bb55'
        - '#559977'
        - '#88bb66'
        - '#bbdd99'
        - '#55aa66'
        - '#bbcc88'
        - '#aadddd'
        - '#66bb55'
        - '#99cccc'
        - '#99bbcc'
        - '#aadd99'
        - '#88bbbb'
        - '#88aabb'
        - '#77bb66'
        - '#88aa55'
        - '#77aaaa'
        - '#7799aa'
        - '#aacc88'
        - '#669999'
        - '#77aa44'
        - '#aabb77'
        - '#558888'
        - '#99cc88'
        - '#447777'
        - '#66aa77'
        - '#ccffee'
        - '#77aa55'
        - '#99bb77'
        - '#bbeedd'
        - '#aaddcc'
        - '#99aa66'
        - '#66aa44'
        - '#99ccbb'
        - '#88bb77'
        - '#88bbaa'
        - '#66aa55'
        - '#779944'
        - '#77aa99'
        - '#559966'
        - '#88aa66'
        - '#ccffdd'
        - '#bbeecc'
        - '#aaddbb'
        - '#77aa66'
        - '#eeffcc'
        - '#669944'
        - '#ddeebb'
        - '#ddffcc'
        - '#779955'
        - '#ccddaa'
        - '#cceebb'
        - '#66aa66'
        - '#bbddaa'
        - '#bbcc99'
        - '#669955'
        - '#aacc99'
        - '#aabb88'
        - '#669977'
        - '#99bb88'
        - '#99aa77'
        - '#88bb88'
        - '#88aa77'
        - '#889966'
        - '#77aa77'
        - '#779966'
        - '#669966'
        - '#cceeee'
        - '#bbdddd'
        - '#bbccdd'
        - '#aacccc'
        - '#aabbcc'
        - '#99bbbb'
        - '#99aabb'
        - '#88aaaa'
        - '#779999'
        - '#ddffee'
        - '#cceedd'
        - '#bbddcc'
        - '#ffffdd'
        - '#ffeedd'
        - '#eeeecc'
        - '#eeffdd'
        - '#ddddbb'
        - '#ddeecc'
        - '#ccccaa'
        - '#ddffdd'
        - '#ccddbb'
        - '#cceecc'
        - '#bbccaa'
        - '#aabb99'
        - '#88aa88'
        - '#eeffff'
        - '#ddeeee'
        - '#ccdddd'
        - '#ffffee'
        - '#ffeeee'
        - '#eeeedd'
        - '#eeffee'
        - '#ddeedd'
        - '#eeeeee'
        - '#ffffff'
    mostGroupedColors:
        - '#66ccbb'
bottomThird:
    averageColor: '#66caba'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    minmaxWhite:
        - '#ffffff'
        - '#447777'
    minmaxRed:
        - '#447777'
        - '#eeffff'
    minmaxGreen:
        - '#66bb55'
        - '#ffffff'
    minmaxBlue:
        - '#447788'
        - '#ffffee'
    mostFrequentColors:
        - '#77bbbb'
    mostSatulightedColors:
        - '#66cccc'
        - '#55bbbb'
        - '#55aabb'
        - '#44aaaa'
        - '#4499aa'
        - '#338899'
        - '#339999'
        - '#66ccbb'
        - '#55bbaa'
        - '#44aa99'
        - '#66bbbb'
        - '#66aabb'
        - '#55aaaa'
        - '#5599aa'
        - '#449999'
        - '#448899'
        - '#338888'
        - '#77ccbb'
        - '#66bbaa'
        - '#55aa99'
        - '#449988'
        - '#77bbbb'
        - '#66aaaa'
        - '#6699aa'
        - '#559999'
        - '#558899'
        - '#448888'
        - '#447788'
        - '#449977'
        - '#99ddcc'
        - '#88ccbb'
        - '#77bbaa'
        - '#66aa99'
        - '#55aa77'
        - '#448877'
        - '#77bb55'
        - '#559977'
        - '#55aa66'
        - '#66bb55'
        - '#99cccc'
        - '#99bbcc'
        - '#88bbbb'
        - '#88aabb'
        - '#77aaaa'
        - '#7799aa'
        - '#669999'
        - '#558888'
        - '#447777'
        - '#66aa77'
        - '#ccffee'
        - '#77aa55'
        - '#bbeedd'
        - '#aaddcc'
        - '#99ccbb'
        - '#88bbaa'
        - '#66aa55'
        - '#77aa99'
        - '#559966'
        - '#ccffdd'
        - '#bbeecc'
        - '#77aa66'
        - '#ddffcc'
        - '#cceebb'
        - '#66aa66'
        - '#88aa77'
        - '#77aa77'
        - '#cceeee'
        - '#bbdddd'
        - '#bbccdd'
        - '#aacccc'
        - '#aabbcc'
        - '#99bbbb'
        - '#99aabb'
        - '#88aaaa'
        - '#779999'
        - '#ddffee'
        - '#cceedd'
        - '#bbddcc'
        - '#ddeecc'
        - '#ddffdd'
        - '#ccddbb'
        - '#cceecc'
        - '#88aa88'
        - '#eeffff'
        - '#ddeeee'
        - '#ccdddd'
        - '#ffffee'
        - '#ffeeee'
        - '#eeffee'
        - '#ddeedd'
        - '#ffffff'
        - '#eeeeee'
    mostGroupedColors:
        - '#66ccbb'
bottomLine:
    averageColor: '#66ccbb'
    lightestColor: '#77ccbb'
    darkestColor: '#66ccbb'
    minmaxWhite:
        - '#77ccbb'
        - '#66ccbb'
    minmaxRed:
        - '#77bbbb'
        - '#66ccbb'
    minmaxGreen:
        - '#66ccbb'
        - '#77bbbb'
    minmaxBlue:
        - '#77bbbb'
        - '#77ccbb'
    mostFrequentColors:
        - '#77bbbb'
    mostSatulightedColors:
        - '#66ccbb'
        - '#77ccbb'
        - '#77bbbb'
    mostGroupedColors:
        - '#66ccbb'
