version: colorful-192x108-16bit-v13palette
palette:
    - note: Most frequent color
      value: '#448833'
      count: 19053
    - note: Most distant color from primary color
      value: '#ffffff'
averageColor: '#4b8d39'
lightestColor: '#ffffff'
darkestColor: '#224422'
mostFrequentColors:
    - value: '#448833'
      count: 18963
    - value: '#bbdd88'
      count: 197
mostSatulightedColors:
    - value: '#ccee88'
      count: 29
    - value: '#448844'
      count: 10
mostGroupedColors:
    - value: '#448833'
      count: 18915
bottomHalf:
    averageColor: '#4a8c38'
    lightestColor: '#ffffff'
    darkestColor: '#224422'
    mostFrequentColors:
        - value: '#448833'
          count: 19053
        - value: '#bbdd88'
          count: 164
    mostSatulightedColors:
        - value: '#ccee88'
          count: 29
        - value: '#448844'
          count: 7
    mostGroupedColors:
        - value: '#448833'
          count: 19035
bottomThird:
    averageColor: '#448833'
    lightestColor: '#ffffff'
    darkestColor: '#224433'
    mostFrequentColors:
        - value: '#448833'
          count: 20547
        - value: '#ffffff'
          count: 29
    mostSatulightedColors:
        - value: '#559933'
          count: 5
        - value: '#224433'
          count: 19
    mostGroupedColors:
        - value: '#448833'
          count: 20480
bottomLine:
    averageColor: '#448833'
    lightestColor: '#558844'
    darkestColor: '#448833'
    mostFrequentColors:
        - value: '#448833'
          count: 20628
    mostSatulightedColors:
        - value: '#558844'
          count: 108
    mostGroupedColors:
        - value: '#448833'
          count: 20520
