version: 5
averageColor: '#4b8d38'
lightestColor: '#ffffff'
darkestColor: '#114411'
minmaxWhite:
    - '#ffffff'
    - '#113311'
minmaxRed:
    - '#445522'
    - '#eeffff'
minmaxGreen:
    - '#449933'
    - '#ffffff'
minmaxBlue:
    - '#445555'
    - '#ffffcc'
mostFrequentColors:
    - '#558844'
mostSatulightedColors:
    - '#ddff99'
    - '#bbee77'
    - '#aaee66'
    - '#bbdd66'
    - '#ccee88'
    - '#aadd55'
    - '#bbee88'
    - '#aadd66'
    - '#bbdd77'
    - '#99dd55'
    - '#99dd66'
    - '#ddffaa'
    - '#bbcc66'
    - '#aadd77'
    - '#ddee99'
    - '#ccee99'
    - '#99dd77'
    - '#aacc66'
    - '#99cc55'
    - '#ccdd88'
    - '#bbee99'
    - '#bbdd88'
    - '#99cc66'
    - '#88cc55'
    - '#bbcc77'
    - '#aadd88'
    - '#88cc66'
    - '#99bb55'
    - '#aacc77'
    - '#eeffbb'
    - '#99cc77'
    - '#88bb44'
    - '#88bb55'
    - '#ddffbb'
    - '#ddeeaa'
    - '#99bb66'
    - '#cceeaa'
    - '#ccdd99'
    - '#77bb55'
    - '#77bb44'
    - '#88bb66'
    - '#bbeeaa'
    - '#bbdd99'
    - '#bbcc88'
    - '#77bb66'
    - '#88aa55'
    - '#aacc88'
    - '#77aa44'
    - '#aabb77'
    - '#99cc88'
    - '#77aa55'
    - '#99bb77'
    - '#66aa44'
    - '#88bb77'
    - '#779944'
    - '#88aa66'
    - '#66aa33'
    - '#ffffcc'
    - '#77aa66'
    - '#eeffcc'
    - '#669944'
    - '#ddeebb'
    - '#ddffcc'
    - '#669933'
    - '#779955'
    - '#ccddaa'
    - '#cceebb'
    - '#bbddaa'
    - '#bbcc99'
    - '#559944'
    - '#669955'
    - '#aacc99'
    - '#aabb88'
    - '#559933'
    - '#99cc99'
    - '#99bb88'
    - '#99aa77'
    - '#449944'
    - '#559955'
    - '#668844'
    - '#337744'
    - '#88aa77'
    - '#449933'
    - '#889966'
    - '#558833'
    - '#558844'
    - '#77aa77'
    - '#779966'
    - '#778855'
    - '#448833'
    - '#448844'
    - '#669966'
    - '#558822'
    - '#557733'
    - '#668855'
    - '#114433'
    - '#336644'
    - '#558855'
    - '#447733'
    - '#448822'
    - '#557744'
    - '#ffffdd'
    - '#224444'
    - '#eeeecc'
    - '#eeffdd'
    - '#88aa99'
    - '#ddeecc'
    - '#ddffdd'
    - '#447722'
    - '#ccddbb'
    - '#447744'
    - '#337733'
    - '#cceecc'
    - '#556633'
    - '#aabb99'
    - '#225533'
    - '#aaccaa'
    - '#99aa88'
    - '#99bb99'
    - '#446622'
    - '#446633'
    - '#889977'
    - '#88aa88'
    - '#446655'
    - '#779977'
    - '#778866'
    - '#335544'
    - '#336633'
    - '#668866'
    - '#667755'
    - '#336622'
    - '#445522'
    - '#557755'
    - '#556644'
    - '#224433'
    - '#114422'
    - '#446644'
    - '#335522'
    - '#445533'
    - '#335533'
    - '#225522'
    - '#113322'
    - '#334422'
    - '#334411'
    - '#224422'
    - '#eeffff'
    - '#778888'
    - '#225511'
    - '#667777'
    - '#445555'
    - '#ffffee'
    - '#334444'
    - '#eeffee'
    - '#223333'
    - '#ddeedd'
    - '#ccddcc'
    - '#224411'
    - '#99aa99'
    - '#889988'
    - '#778877'
    - '#667766'
    - '#445544'
    - '#114411'
    - '#334433'
    - '#223322'
    - '#113311'
    - '#ffffff'
    - '#eeeeee'
    - '#333333'
mostGroupedColors:
    - '#448833'
bottomHalf:
    averageColor: '#4a8c38'
    lightestColor: '#ffffff'
    darkestColor: '#114411'
    minmaxWhite:
        - '#ffffff'
        - '#113311'
    minmaxRed:
        - '#445522'
        - '#eeffff'
    minmaxGreen:
        - '#449933'
        - '#ffffff'
    minmaxBlue:
        - '#445555'
        - '#ffffcc'
    mostFrequentColors:
        - '#558844'
    mostSatulightedColors:
        - '#ddff99'
        - '#bbee77'
        - '#bbdd66'
        - '#ccee88'
        - '#aadd55'
        - '#bbee88'
        - '#aadd66'
        - '#bbdd77'
        - '#99dd55'
        - '#99dd66'
        - '#ddffaa'
        - '#aadd77'
        - '#ddee99'
        - '#ccee99'
        - '#99dd77'
        - '#aacc66'
        - '#99cc55'
        - '#ccdd88'
        - '#bbee99'
        - '#bbdd88'
        - '#99cc66'
        - '#88cc55'
        - '#bbcc77'
        - '#aadd88'
        - '#88cc66'
        - '#aacc77'
        - '#eeffbb'
        - '#99cc77'
        - '#88bb55'
        - '#ddffbb'
        - '#ddeeaa'
        - '#99bb66'
        - '#cceeaa'
        - '#ccdd99'
        - '#88bb66'
        - '#bbeeaa'
        - '#bbdd99'
        - '#bbcc88'
        - '#88aa55'
        - '#aacc88'
        - '#aabb77'
        - '#99cc88'
        - '#77aa55'
        - '#99bb77'
        - '#88bb77'
        - '#88aa66'
        - '#ffffcc'
        - '#77aa66'
        - '#eeffcc'
        - '#669944'
        - '#ddeebb'
        - '#ddffcc'
        - '#779955'
        - '#ccddaa'
        - '#cceebb'
        - '#bbddaa'
        - '#bbcc99'
        - '#559944'
        - '#669955'
        - '#aacc99'
        - '#aabb88'
        - '#559933'
        - '#99cc99'
        - '#99bb88'
        - '#99aa77'
        - '#449944'
        - '#559955'
        - '#668844'
        - '#337744'
        - '#88aa77'
        - '#449933'
        - '#889966'
        - '#558833'
        - '#558844'
        - '#77aa77'
        - '#779966'
        - '#778855'
        - '#448833'
        - '#448844'
        - '#669966'
        - '#557733'
        - '#668855'
        - '#114433'
        - '#558855'
        - '#447733'
        - '#448822'
        - '#557744'
        - '#ffffdd'
        - '#224444'
        - '#eeeecc'
        - '#eeffdd'
        - '#88aa99'
        - '#ddeecc'
        - '#ddffdd'
        - '#447722'
        - '#ccddbb'
        - '#447744'
        - '#337733'
        - '#cceecc'
        - '#556633'
        - '#aabb99'
        - '#225533'
        - '#aaccaa'
        - '#99aa88'
        - '#99bb99'
        - '#446622'
        - '#446633'
        - '#889977'
        - '#88aa88'
        - '#446655'
        - '#779977'
        - '#778866'
        - '#335544'
        - '#336633'
        - '#668866'
        - '#667755'
        - '#336622'
        - '#445522'
        - '#557755'
        - '#556644'
        - '#224433'
        - '#114422'
        - '#446644'
        - '#335522'
        - '#445533'
        - '#335533'
        - '#225522'
        - '#113322'
        - '#334422'
        - '#224422'
        - '#eeffff'
        - '#778888'
        - '#667777'
        - '#445555'
        - '#ffffee'
        - '#334444'
        - '#eeffee'
        - '#223333'
        - '#ddeedd'
        - '#ccddcc'
        - '#224411'
        - '#99aa99'
        - '#889988'
        - '#778877'
        - '#667766'
        - '#445544'
        - '#114411'
        - '#334433'
        - '#223322'
        - '#113311'
        - '#ffffff'
        - '#333333'
    mostGroupedColors:
        - '#448833'
bottomThird:
    averageColor: '#448833'
    lightestColor: '#ffffff'
    darkestColor: '#113311'
    minmaxWhite:
        - '#ffffff'
        - '#113311'
    minmaxRed:
        - '#223322'
        - '#eeffff'
    minmaxGreen:
        - '#449933'
        - '#ffffff'
    minmaxBlue:
        - '#223333'
        - '#ffffee'
    mostFrequentColors:
        - '#558844'
    mostSatulightedColors:
        - '#aacc88'
        - '#559944'
        - '#669955'
        - '#aacc99'
        - '#559933'
        - '#99cc99'
        - '#99bb88'
        - '#449933'
        - '#558833'
        - '#558844'
        - '#77aa77'
        - '#779966'
        - '#448833'
        - '#448844'
        - '#669966'
        - '#668855'
        - '#114433'
        - '#558855'
        - '#447733'
        - '#557744'
        - '#ddeecc'
        - '#ddffdd'
        - '#447722'
        - '#447744'
        - '#cceecc'
        - '#aabb99'
        - '#aaccaa'
        - '#99aa88'
        - '#446633'
        - '#88aa88'
        - '#779977'
        - '#668866'
        - '#336633'
        - '#336622'
        - '#224433'
        - '#114422'
        - '#335522'
        - '#225522'
        - '#113322'
        - '#224422'
        - '#eeffff'
        - '#ffffee'
        - '#eeffee'
        - '#223333'
        - '#ddeedd'
        - '#99aa99'
        - '#113311'
        - '#223322'
        - '#ffffff'
    mostGroupedColors:
        - '#448833'
bottomLine:
    averageColor: '#448833'
    lightestColor: '#558844'
    darkestColor: '#449933'
    minmaxWhite:
        - '#558844'
        - '#448833'
    minmaxRed:
        - '#558844'
        - '#449933'
    minmaxGreen:
        - '#449933'
        - '#558844'
    minmaxBlue:
        - '#448844'
        - '#449933'
    mostFrequentColors:
        - '#558844'
    mostSatulightedColors:
        - '#449933'
        - '#558844'
        - '#448833'
        - '#448844'
    mostGroupedColors:
        - '#448833'
