version: colorful-192x108-16bit-v12palette
palette:
    - '#448833'
    - '#ffffff'
averageColor: '#4b8d39'
lightestColor: '#ffffff'
darkestColor: '#224422'
mostFrequentColors:
    - '#448833'
    - '#bbdd88'
mostSatulightedColors:
    - '#ccee88'
    - '#448844'
mostGroupedColors:
    - '#448833'
bottomHalf:
    averageColor: '#4a8c38'
    lightestColor: '#ffffff'
    darkestColor: '#224422'
    mostFrequentColors:
        - '#448833'
        - '#bbdd88'
    mostSatulightedColors:
        - '#ccee88'
        - '#448844'
    mostGroupedColors:
        - '#448833'
bottomThird:
    averageColor: '#448833'
    lightestColor: '#ffffff'
    darkestColor: '#224433'
    mostFrequentColors:
        - '#448833'
        - '#ffffff'
    mostSatulightedColors:
        - '#559933'
        - '#224433'
    mostGroupedColors:
        - '#448833'
bottomLine:
    averageColor: '#448833'
    lightestColor: '#558844'
    darkestColor: '#448833'
    mostFrequentColors:
        - '#448833'
    mostSatulightedColors:
        - '#558844'
    mostGroupedColors:
        - '#448833'
