version: colorful-192x108-16bit-v12palette
palette:
    - '#cccc11'
    - '#000000'
averageColor: '#cbcc12'
lightestColor: '#ffffcc'
darkestColor: '#889900'
mostFrequentColors:
    - '#cccc11'
    - '#ffffbb'
mostSatulightedColors:
    - '#eeff77'
mostGroupedColors:
    - '#cccc11'
bottomHalf:
    averageColor: '#cbcb12'
    lightestColor: '#ffffcc'
    darkestColor: '#889900'
    mostFrequentColors:
        - '#cccc11'
        - '#ffffbb'
    mostSatulightedColors:
        - '#eedd77'
    mostGroupedColors:
        - '#cccc11'
bottomThird:
    averageColor: '#cccc11'
    lightestColor: '#eeff99'
    darkestColor: '#888800'
    mostFrequentColors:
        - '#cccc11'
    mostSatulightedColors:
        - '#ddee77'
    mostGroupedColors:
        - '#cccc11'
bottomLine:
    averageColor: '#cccc11'
    lightestColor: '#cccc33'
    darkestColor: '#cccc11'
    mostFrequentColors:
        - '#cccc11'
    mostSatulightedColors:
        - '#cccc33'
    mostGroupedColors:
        - '#cccc11'
