version: colorful-192x108-16bit-v14palette
palette:
    - note: The most common color to appear at the bottom of the wallpaper.
      value: '#66ccbb'
      count: 17263
    - note: The color farthest from the primary color.
      value: '#000000'
paletteCandidates:
    - note: 1st most satulighted color of the bottom half of the wallpaper
      value: '#55ccbb'
      count: 1
    - note: 2nd most satulighted color of the bottom half of the wallpaper
      value: '#cceeaa'
      count: 1
    - note: 1st most grouped color of the bottom half of the wallpaper
      value: '#66ccbb'
      count: 17263
    - note: 1st most frequent color of the bottom half of the wallpaper
      value: '#66ccbb'
      count: 17263
    - note: 2nd most frequent color of the bottom half of the wallpaper
      value: '#ffffff'
      count: 103
    - note: The darkest color of the bottom half of the wallpaper
      value: '#66aa55'
    - note: The lightest color of the bottom half of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom third of the wallpaper
      value: '#66cccc'
      count: 1
    - note: 2nd most satulighted color of the bottom third of the wallpaper
      value: '#559977'
      count: 4
    - note: 3rd most satulighted color of the bottom third of the wallpaper
      value: '#77aa55'
      count: 154
    - note: 1st most grouped color of the bottom third of the wallpaper
      value: '#66ccbb'
      count: 18781
    - note: 1st most frequent color of the bottom third of the wallpaper
      value: '#66ccbb'
      count: 18781
    - note: 2nd most frequent color of the bottom third of the wallpaper
      value: '#ffffff'
      count: 50
    - note: The darkest color of the bottom third of the wallpaper
      value: '#66aa55'
    - note: The lightest color of the bottom third of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the whole wallpaper
      value: '#55ccbb'
      count: 9
    - note: 2nd most satulighted color of the whole wallpaper
      value: '#66bb77'
      count: 2
    - note: 3rd most satulighted color of the whole wallpaper
      value: '#77bb55'
      count: 3
    - note: 1st most grouped color of the whole wallpaper
      value: '#66ccbb'
      count: 17773
    - note: 1st most frequent color of the whole wallpaper
      value: '#66ccbb'
      count: 17775
    - note: 2nd most frequent color of the whole wallpaper
      value: '#ffffff'
      count: 88
    - note: The darkest color of the whole wallpaper
      value: '#66aa55'
    - note: The lightest color of the whole wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom line of the wallpaper
      value: '#66ccbb'
      count: 20628
    - note: 1st most grouped color of the bottom line of the wallpaper
      value: '#66ccbb'
      count: 20520
    - note: 1st most frequent color of the bottom line of the wallpaper
      value: '#66ccbb'
      count: 20628
    - note: The darkest color of the bottom line of the wallpaper
      value: '#66ccbb'
    - note: The lightest color of the bottom line of the wallpaper
      value: '#77ccbb'
averageColor: '#6dccb8'
lightestColor: '#ffffff'
darkestColor: '#66aa55'
mostFrequentColors:
    - value: '#66ccbb'
      count: 17775
    - value: '#ffffff'
      count: 88
mostSatulightedColors:
    - value: '#55ccbb'
      count: 9
    - value: '#66bb77'
      count: 2
    - value: '#77bb55'
      count: 3
mostGroupedColors:
    - value: '#66ccbb'
      count: 17773
bottomHalf:
    averageColor: '#6ccbb8'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    mostFrequentColors:
        - value: '#66ccbb'
          count: 17263
        - value: '#ffffff'
          count: 103
    mostSatulightedColors:
        - value: '#55ccbb'
          count: 1
        - value: '#cceeaa'
          count: 1
    mostGroupedColors:
        - value: '#66ccbb'
          count: 17263
bottomThird:
    averageColor: '#66caba'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    mostFrequentColors:
        - value: '#66ccbb'
          count: 18781
        - value: '#ffffff'
          count: 50
    mostSatulightedColors:
        - value: '#66cccc'
          count: 1
        - value: '#559977'
          count: 4
        - value: '#77aa55'
          count: 154
    mostGroupedColors:
        - value: '#66ccbb'
          count: 18781
bottomLine:
    averageColor: '#66ccbb'
    lightestColor: '#77ccbb'
    darkestColor: '#66ccbb'
    mostFrequentColors:
        - value: '#66ccbb'
          count: 20628
    mostSatulightedColors:
        - value: '#66ccbb'
          count: 20628
    mostGroupedColors:
        - value: '#66ccbb'
          count: 20520
