version: colorful-192x108-16bit-v14palette
palette:
    - note: The darkest color of the bottom line of the wallpaper that is the most
          similar color to the average color of the bottom third of the
          wallpaper.
      value: '#335522'
    - note: The color farthest from the primary color.
      value: '#ffffff'
    - note: 1. the most satulighted color of the bottom half of the wallpaper which is
          distant enough (10%) and hue-distant enough (30°) from all other
          palette colors.
      value: '#eecc55'
      count: 10
averageColor: '#3c5a24'
lightestColor: '#eedd77'
darkestColor: '#333311'
mostFrequentColors:
    - value: '#335522'
      count: 18305
    - value: '#eecc55'
      count: 185
mostSatulightedColors:
    - value: '#eecc55'
      count: 185
mostGroupedColors:
    - value: '#335522'
      count: 17785
bottomHalf:
    averageColor: '#3c5a23'
    lightestColor: '#888877'
    darkestColor: '#555500'
    mostFrequentColors:
        - value: '#335522'
          count: 18696
        - value: '#ddbb33'
          count: 238
    mostSatulightedColors:
        - value: '#eecc55'
          count: 10
    mostGroupedColors:
        - value: '#335522'
          count: 18574
bottomThird:
    averageColor: '#355623'
    lightestColor: '#998877'
    darkestColor: '#333300'
    mostFrequentColors:
        - value: '#335522'
          count: 19533
        - value: '#ddaa22'
          count: 88
    mostSatulightedColors:
        - value: '#eebb33'
          count: 4
    mostGroupedColors:
        - value: '#335522'
          count: 19485
bottomLine:
    averageColor: '#335533'
    lightestColor: '#335533'
    darkestColor: '#335522'
    mostFrequentColors:
        - value: '#335533'
          count: 20304
    mostSatulightedColors:
        - value: '#335522'
          count: 432
    mostGroupedColors:
        - value: '#335533'
          count: 19656
