version: colorful-192x108-16bit-v13palette
palette:
    - note: Most frequent color
      value: '#66bb99'
      count: 18423
    - note: Most distant color from primary color
      value: '#000000'
    - note: Most satulighted color which is distant enough (10%) and hue-distant
          enough (30°) from all other palette colors
      value: '#eeaa55'
      count: 1
averageColor: '#72bc99'
lightestColor: '#ffffff'
darkestColor: '#ee8833'
mostFrequentColors:
    - value: '#66bb99'
      count: 18659
    - value: '#ffeecc'
      count: 768
    - value: '#ee9944'
      count: 598
mostSatulightedColors:
    - value: '#55bb99'
      count: 141
    - value: '#ee9955'
      count: 1
    - value: '#99aa66'
      count: 1
mostGroupedColors:
    - value: '#66bb99'
      count: 18652
bottomHalf:
    averageColor: '#73bc99'
    lightestColor: '#ffffff'
    darkestColor: '#ee8833'
    mostFrequentColors:
        - value: '#66bb99'
          count: 18423
        - value: '#ffeecc'
          count: 775
        - value: '#ee9944'
          count: 689
    mostSatulightedColors:
        - value: '#55bb99'
          count: 198
        - value: '#eeaa55'
          count: 1
        - value: '#99aa66'
          count: 2
    mostGroupedColors:
        - value: '#66bb99'
          count: 18403
bottomThird:
    averageColor: '#6bbc99'
    lightestColor: '#ffffff'
    darkestColor: '#cc9944'
    mostFrequentColors:
        - value: '#66bb99'
          count: 19592
        - value: '#ffeecc'
          count: 303
        - value: '#ee9944'
          count: 262
    mostSatulightedColors:
        - value: '#55bb99'
          count: 154
        - value: '#ee9944'
          count: 262
        - value: '#ffffcc'
          count: 1
    mostGroupedColors:
        - value: '#66bb99'
          count: 19573
bottomLine:
    averageColor: '#66bb99'
    lightestColor: '#66bb99'
    darkestColor: '#55bb99'
    mostFrequentColors:
        - value: '#66bb99'
          count: 20628
    mostSatulightedColors:
        - value: '#55bb99'
          count: 108
    mostGroupedColors:
        - value: '#66bb99'
          count: 20628
