version: colorful-192x108-16bit-v14palette
palette:
    - note: The most common color to appear at the bottom of the wallpaper.
      value: '#66bb99'
      count: 18423
    - note: The color farthest from the primary color.
      value: '#000000'
    - note: 2nd most satulighted color of the bottom half of the wallpaper which is
          distant enough (10%) and hue-distant enough (30°) from all other
          palette colors.
      value: '#eeaa55'
      count: 1
paletteCandidates:
    - note: 1st most satulighted color of the bottom half of the wallpaper
      value: '#55bb99'
      count: 198
    - note: 2nd most satulighted color of the bottom half of the wallpaper
      value: '#eeaa55'
      count: 1
    - note: 3rd most satulighted color of the bottom half of the wallpaper
      value: '#99aa66'
      count: 2
    - note: 1st most grouped color of the bottom half of the wallpaper
      value: '#66bb99'
      count: 18403
    - note: 1st most frequent color of the bottom half of the wallpaper
      value: '#66bb99'
      count: 18423
    - note: 2nd most frequent color of the bottom half of the wallpaper
      value: '#ffeecc'
      count: 775
    - note: 3rd most frequent color of the bottom half of the wallpaper
      value: '#ee9944'
      count: 689
    - note: The darkest color of the bottom half of the wallpaper
      value: '#ee8833'
    - note: The lightest color of the bottom half of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom third of the wallpaper
      value: '#55bb99'
      count: 154
    - note: 2nd most satulighted color of the bottom third of the wallpaper
      value: '#ee9944'
      count: 262
    - note: 3rd most satulighted color of the bottom third of the wallpaper
      value: '#ffffcc'
      count: 1
    - note: 1st most grouped color of the bottom third of the wallpaper
      value: '#66bb99'
      count: 19573
    - note: 1st most frequent color of the bottom third of the wallpaper
      value: '#66bb99'
      count: 19592
    - note: 2nd most frequent color of the bottom third of the wallpaper
      value: '#ffeecc'
      count: 303
    - note: 3rd most frequent color of the bottom third of the wallpaper
      value: '#ee9944'
      count: 262
    - note: The darkest color of the bottom third of the wallpaper
      value: '#cc9944'
    - note: The lightest color of the bottom third of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the whole wallpaper
      value: '#55bb99'
      count: 141
    - note: 2nd most satulighted color of the whole wallpaper
      value: '#ee9955'
      count: 1
    - note: 3rd most satulighted color of the whole wallpaper
      value: '#99aa66'
      count: 1
    - note: 1st most grouped color of the whole wallpaper
      value: '#66bb99'
      count: 18652
    - note: 1st most frequent color of the whole wallpaper
      value: '#66bb99'
      count: 18659
    - note: 2nd most frequent color of the whole wallpaper
      value: '#ffeecc'
      count: 768
    - note: 3rd most frequent color of the whole wallpaper
      value: '#ee9944'
      count: 598
    - note: The darkest color of the whole wallpaper
      value: '#ee8833'
    - note: The lightest color of the whole wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom line of the wallpaper
      value: '#55bb99'
      count: 108
    - note: 1st most grouped color of the bottom line of the wallpaper
      value: '#66bb99'
      count: 20628
    - note: 1st most frequent color of the bottom line of the wallpaper
      value: '#66bb99'
      count: 20628
    - note: The darkest color of the bottom line of the wallpaper
      value: '#55bb99'
    - note: The lightest color of the bottom line of the wallpaper
      value: '#66bb99'
averageColor: '#72bc99'
lightestColor: '#ffffff'
darkestColor: '#ee8833'
mostFrequentColors:
    - value: '#66bb99'
      count: 18659
    - value: '#ffeecc'
      count: 768
    - value: '#ee9944'
      count: 598
mostSatulightedColors:
    - value: '#55bb99'
      count: 141
    - value: '#ee9955'
      count: 1
    - value: '#99aa66'
      count: 1
mostGroupedColors:
    - value: '#66bb99'
      count: 18652
bottomHalf:
    averageColor: '#73bc99'
    lightestColor: '#ffffff'
    darkestColor: '#ee8833'
    mostFrequentColors:
        - value: '#66bb99'
          count: 18423
        - value: '#ffeecc'
          count: 775
        - value: '#ee9944'
          count: 689
    mostSatulightedColors:
        - value: '#55bb99'
          count: 198
        - value: '#eeaa55'
          count: 1
        - value: '#99aa66'
          count: 2
    mostGroupedColors:
        - value: '#66bb99'
          count: 18403
bottomThird:
    averageColor: '#6bbc99'
    lightestColor: '#ffffff'
    darkestColor: '#cc9944'
    mostFrequentColors:
        - value: '#66bb99'
          count: 19592
        - value: '#ffeecc'
          count: 303
        - value: '#ee9944'
          count: 262
    mostSatulightedColors:
        - value: '#55bb99'
          count: 154
        - value: '#ee9944'
          count: 262
        - value: '#ffffcc'
          count: 1
    mostGroupedColors:
        - value: '#66bb99'
          count: 19573
bottomLine:
    averageColor: '#66bb99'
    lightestColor: '#66bb99'
    darkestColor: '#55bb99'
    mostFrequentColors:
        - value: '#66bb99'
          count: 20628
    mostSatulightedColors:
        - value: '#55bb99'
          count: 108
    mostGroupedColors:
        - value: '#66bb99'
          count: 20628
