version: colorful-192x108-16bit-v14palette
palette:
    - note: The most common color to appear at the bottom of the wallpaper.
      value: '#448833'
      count: 19053
    - note: The color farthest from the primary color.
      value: '#ffffff'
paletteCandidates:
    - note: 1st most satulighted color of the bottom half of the wallpaper
      value: '#ccee88'
      count: 29
    - note: 2nd most satulighted color of the bottom half of the wallpaper
      value: '#448844'
      count: 7
    - note: 1st most grouped color of the bottom half of the wallpaper
      value: '#448833'
      count: 19035
    - note: 1st most frequent color of the bottom half of the wallpaper
      value: '#448833'
      count: 19053
    - note: 2nd most frequent color of the bottom half of the wallpaper
      value: '#bbdd88'
      count: 164
    - note: The darkest color of the bottom half of the wallpaper
      value: '#224422'
    - note: The lightest color of the bottom half of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom third of the wallpaper
      value: '#559933'
      count: 5
    - note: 2nd most satulighted color of the bottom third of the wallpaper
      value: '#224433'
      count: 19
    - note: 1st most grouped color of the bottom third of the wallpaper
      value: '#448833'
      count: 20480
    - note: 1st most frequent color of the bottom third of the wallpaper
      value: '#448833'
      count: 20547
    - note: 2nd most frequent color of the bottom third of the wallpaper
      value: '#ffffff'
      count: 29
    - note: The darkest color of the bottom third of the wallpaper
      value: '#224433'
    - note: The lightest color of the bottom third of the wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the whole wallpaper
      value: '#ccee88'
      count: 29
    - note: 2nd most satulighted color of the whole wallpaper
      value: '#448844'
      count: 10
    - note: 1st most grouped color of the whole wallpaper
      value: '#448833'
      count: 18915
    - note: 1st most frequent color of the whole wallpaper
      value: '#448833'
      count: 18963
    - note: 2nd most frequent color of the whole wallpaper
      value: '#bbdd88'
      count: 197
    - note: The darkest color of the whole wallpaper
      value: '#224422'
    - note: The lightest color of the whole wallpaper
      value: '#ffffff'
    - note: 1st most satulighted color of the bottom line of the wallpaper
      value: '#558844'
      count: 108
    - note: 1st most grouped color of the bottom line of the wallpaper
      value: '#448833'
      count: 20520
    - note: 1st most frequent color of the bottom line of the wallpaper
      value: '#448833'
      count: 20628
    - note: The darkest color of the bottom line of the wallpaper
      value: '#448833'
    - note: The lightest color of the bottom line of the wallpaper
      value: '#558844'
averageColor: '#4b8d39'
lightestColor: '#ffffff'
darkestColor: '#224422'
mostFrequentColors:
    - value: '#448833'
      count: 18963
    - value: '#bbdd88'
      count: 197
mostSatulightedColors:
    - value: '#ccee88'
      count: 29
    - value: '#448844'
      count: 10
mostGroupedColors:
    - value: '#448833'
      count: 18915
bottomHalf:
    averageColor: '#4a8c38'
    lightestColor: '#ffffff'
    darkestColor: '#224422'
    mostFrequentColors:
        - value: '#448833'
          count: 19053
        - value: '#bbdd88'
          count: 164
    mostSatulightedColors:
        - value: '#ccee88'
          count: 29
        - value: '#448844'
          count: 7
    mostGroupedColors:
        - value: '#448833'
          count: 19035
bottomThird:
    averageColor: '#448833'
    lightestColor: '#ffffff'
    darkestColor: '#224433'
    mostFrequentColors:
        - value: '#448833'
          count: 20547
        - value: '#ffffff'
          count: 29
    mostSatulightedColors:
        - value: '#559933'
          count: 5
        - value: '#224433'
          count: 19
    mostGroupedColors:
        - value: '#448833'
          count: 20480
bottomLine:
    averageColor: '#448833'
    lightestColor: '#558844'
    darkestColor: '#448833'
    mostFrequentColors:
        - value: '#448833'
          count: 20628
    mostSatulightedColors:
        - value: '#558844'
          count: 108
    mostGroupedColors:
        - value: '#448833'
          count: 20520
