version: colorful-1920x1080-16bit-v11
palette:
    - '#334422'
    - '#ffffff'
    - '#bb9922'
averageColor: '#ba9b29'
lightestColor: '#ffffff'
darkestColor: '#223300'
mostFrequentColors:
    - '#bb9922'
    - '#eeeeaa'
    - '#334422'
mostSatulightedColors:
    - '#ffdd88'
    - '#eeffbb'
mostGroupedColors:
    - '#bb9922'
bottomHalf:
    averageColor: '#b89926'
    lightestColor: '#ffffff'
    darkestColor: '#443300'
    mostFrequentColors:
        - '#bb9922'
        - '#334422'
        - '#eeeeaa'
    mostSatulightedColors:
        - '#ffdd99'
        - '#bbcc99'
    mostGroupedColors:
        - '#bb9922'
bottomThird:
    averageColor: '#ba9922'
    lightestColor: '#ffffff'
    darkestColor: '#444400'
    mostFrequentColors:
        - '#bb9922'
        - '#334422'
        - '#ffffee'
    mostSatulightedColors:
        - '#ddbb66'
    mostGroupedColors:
        - '#bb9922'
bottomLine:
    averageColor: '#bb9921'
    lightestColor: '#bb9922'
    darkestColor: '#bb9911'
    mostFrequentColors:
        - '#bb9922'
    mostSatulightedColors:
        - '#bb9922'
    mostGroupedColors:
        - '#bb9922'
