version: 5
averageColor: '#72bc99'
lightestColor: '#ffffff'
darkestColor: '#cc8833'
minmaxWhite:
    - '#ffffff'
    - '#559988'
minmaxRed:
    - '#ee8833'
    - '#eeffff'
minmaxGreen:
    - '#66bb77'
    - '#ffffff'
minmaxBlue:
    - '#669999'
    - '#ffffcc'
mostFrequentColors:
    - '#66aa99'
mostSatulightedColors:
    - '#55bbaa'
    - '#55aaaa'
    - '#55bb99'
    - '#ee9955'
    - '#eeaa55'
    - '#ffcc88'
    - '#eeaa66'
    - '#eebb66'
    - '#ee9944'
    - '#eeaa44'
    - '#ee8844'
    - '#eebb77'
    - '#eeaa77'
    - '#ee8833'
    - '#ee9933'
    - '#66bbaa'
    - '#dd9955'
    - '#ddaa55'
    - '#dd8855'
    - '#dd9944'
    - '#dd8844'
    - '#ddaa44'
    - '#55aa99'
    - '#ddaa66'
    - '#dd9966'
    - '#55bb88'
    - '#eebb88'
    - '#eecc88'
    - '#dd8833'
    - '#dd9933'
    - '#ddbb77'
    - '#ddaa77'
    - '#dd9977'
    - '#ddcc77'
    - '#66bb99'
    - '#cc9944'
    - '#cc8844'
    - '#ccaa44'
    - '#cc9955'
    - '#ccaa55'
    - '#cc8855'
    - '#ffddaa'
    - '#ffeeaa'
    - '#cc8833'
    - '#cc9933'
    - '#55aa88'
    - '#66aaaa'
    - '#cc9966'
    - '#ccaa66'
    - '#eebb99'
    - '#eecc99'
    - '#eedd99'
    - '#77cc99'
    - '#ddbb88'
    - '#ddcc88'
    - '#ddaa88'
    - '#66bb88'
    - '#bb9955'
    - '#bbaa55'
    - '#77bbaa'
    - '#ccaa77'
    - '#ccbb77'
    - '#66aa99'
    - '#559988'
    - '#bbaa66'
    - '#bb9966'
    - '#88ccaa'
    - '#ffddbb'
    - '#ffeebb'
    - '#77bb99'
    - '#eeddaa'
    - '#eeccaa'
    - '#66bb77'
    - '#aa9955'
    - '#aaaa55'
    - '#ddcc99'
    - '#ddbb99'
    - '#dddd99'
    - '#66aa88'
    - '#cccc88'
    - '#bbbb77'
    - '#bbaa77'
    - '#77bb88'
    - '#669999'
    - '#aaaa66'
    - '#aa9966'
    - '#99bb77'
    - '#99aa66'
    - '#99ccbb'
    - '#88bbaa'
    - '#77aa99'
    - '#88aa66'
    - '#77bb77'
    - '#ffeecc'
    - '#ffffcc'
    - '#ffddcc'
    - '#669988'
    - '#eeddbb'
    - '#eeeebb'
    - '#aaddbb'
    - '#eeffcc'
    - '#ddddaa'
    - '#ddccaa'
    - '#ddeebb'
    - '#99ccaa'
    - '#ccbb99'
    - '#ccddaa'
    - '#cceebb'
    - '#88bb99'
    - '#bbddaa'
    - '#bbcc99'
    - '#bbbb88'
    - '#77aa88'
    - '#aaddaa'
    - '#aacc99'
    - '#aaaa77'
    - '#aa9977'
    - '#99cc99'
    - '#99bb88'
    - '#99aa77'
    - '#999966'
    - '#88bb88'
    - '#88aa77'
    - '#77aa77'
    - '#99bbbb'
    - '#ddffee'
    - '#cceedd'
    - '#bbddcc'
    - '#aaccbb'
    - '#ffeedd'
    - '#ffffdd'
    - '#99bbaa'
    - '#eeeecc'
    - '#eeddcc'
    - '#eeffdd'
    - '#ddddbb'
    - '#88aa99'
    - '#ddeecc'
    - '#ccccaa'
    - '#ddffdd'
    - '#779988'
    - '#ccddbb'
    - '#cceecc'
    - '#bbbb99'
    - '#bbccaa'
    - '#bbddbb'
    - '#aaaa88'
    - '#aaccaa'
    - '#999977'
    - '#99aa88'
    - '#99bb99'
    - '#889977'
    - '#88aa88'
    - '#eeffff'
    - '#ddeeee'
    - '#ccdddd'
    - '#ffffee'
    - '#ffeeee'
    - '#eeeedd'
    - '#ddddcc'
    - '#eeffee'
    - '#ddeedd'
    - '#ccddcc'
    - '#bbccbb'
    - '#aabbaa'
    - '#99aa99'
    - '#ffffff'
    - '#eeeeee'
mostGroupedColors:
    - '#66bb99'
bottomHalf:
    averageColor: '#73bc99'
    lightestColor: '#ffffff'
    darkestColor: '#cc8833'
    minmaxWhite:
        - '#ffffff'
        - '#559988'
    minmaxRed:
        - '#ee8833'
        - '#eeffff'
    minmaxGreen:
        - '#66bb88'
        - '#ffffff'
    minmaxBlue:
        - '#669999'
        - '#ffffcc'
    mostFrequentColors:
        - '#66aa99'
    mostSatulightedColors:
        - '#55bb99'
        - '#ee9955'
        - '#eeaa55'
        - '#eeaa66'
        - '#ee9944'
        - '#ee8844'
        - '#eeaa44'
        - '#eebb77'
        - '#eeaa77'
        - '#ee8833'
        - '#ee9933'
        - '#66bbaa'
        - '#dd9955'
        - '#ddaa55'
        - '#dd8855'
        - '#dd9944'
        - '#dd8844'
        - '#ddaa44'
        - '#55aa99'
        - '#dd9966'
        - '#ddaa66'
        - '#eebb88'
        - '#eecc88'
        - '#dd8833'
        - '#dd9933'
        - '#ddaa77'
        - '#ddbb77'
        - '#dd9977'
        - '#ddcc77'
        - '#66bb99'
        - '#cc9944'
        - '#ccaa44'
        - '#cc9955'
        - '#ccaa55'
        - '#cc8855'
        - '#ffddaa'
        - '#ffeeaa'
        - '#cc8833'
        - '#55aa88'
        - '#cc9966'
        - '#ccaa66'
        - '#eebb99'
        - '#eecc99'
        - '#eedd99'
        - '#77cc99'
        - '#ddbb88'
        - '#ddaa88'
        - '#ddcc88'
        - '#66bb88'
        - '#bb9955'
        - '#bbaa55'
        - '#77bbaa'
        - '#ccaa77'
        - '#66aa99'
        - '#559988'
        - '#bbaa66'
        - '#bb9966'
        - '#88ccaa'
        - '#ffddbb'
        - '#ffeebb'
        - '#77bb99'
        - '#eeccaa'
        - '#eeddaa'
        - '#ddcc99'
        - '#ddbb99'
        - '#66aa88'
        - '#bbbb77'
        - '#77bb88'
        - '#669999'
        - '#aaaa66'
        - '#aa9966'
        - '#99aa66'
        - '#99ccbb'
        - '#88bbaa'
        - '#77aa99'
        - '#ffeecc'
        - '#ffffcc'
        - '#ffddcc'
        - '#669988'
        - '#eeddbb'
        - '#eeeebb'
        - '#aaddbb'
        - '#eeffcc'
        - '#ddddaa'
        - '#ddccaa'
        - '#99ccaa'
        - '#ccbb99'
        - '#cceebb'
        - '#88bb99'
        - '#bbddaa'
        - '#77aa88'
        - '#aaddaa'
        - '#aaaa77'
        - '#aa9977'
        - '#99cc99'
        - '#99aa77'
        - '#999966'
        - '#88aa77'
        - '#77aa77'
        - '#99bbbb'
        - '#ddffee'
        - '#cceedd'
        - '#bbddcc'
        - '#aaccbb'
        - '#ffeedd'
        - '#ffffdd'
        - '#99bbaa'
        - '#eeeecc'
        - '#eeddcc'
        - '#eeffdd'
        - '#ddddbb'
        - '#88aa99'
        - '#ddeecc'
        - '#ddffdd'
        - '#779988'
        - '#ccddbb'
        - '#cceecc'
        - '#bbddbb'
        - '#aaccaa'
        - '#999977'
        - '#99aa88'
        - '#99bb99'
        - '#889977'
        - '#88aa88'
        - '#eeffff'
        - '#ddeeee'
        - '#ccdddd'
        - '#ffffee'
        - '#ffeeee'
        - '#eeeedd'
        - '#eeffee'
        - '#ddeedd'
        - '#ccddcc'
        - '#bbccbb'
        - '#aabbaa'
        - '#99aa99'
        - '#ffffff'
        - '#eeeeee'
    mostGroupedColors:
        - '#66bb99'
bottomThird:
    averageColor: '#6bbb99'
    lightestColor: '#ffffff'
    darkestColor: '#dd9933'
    minmaxWhite:
        - '#ffffff'
        - '#559988'
    minmaxRed:
        - '#ee9933'
        - '#eeffff'
    minmaxGreen:
        - '#66bb88'
        - '#ffffff'
    minmaxBlue:
        - '#669999'
        - '#ffffcc'
    mostFrequentColors:
        - '#66aa99'
    mostSatulightedColors:
        - '#55bb99'
        - '#ee9955'
        - '#eeaa44'
        - '#ee9944'
        - '#ee9933'
        - '#66bbaa'
        - '#ddaa55'
        - '#dd9955'
        - '#ddaa44'
        - '#dd9944'
        - '#55aa99'
        - '#ddaa66'
        - '#dd9966'
        - '#dd9933'
        - '#ddbb77'
        - '#ddaa77'
        - '#66bb99'
        - '#ccaa44'
        - '#cc9944'
        - '#ccaa55'
        - '#cc9955'
        - '#55aa88'
        - '#ccaa66'
        - '#cc9966'
        - '#eecc99'
        - '#77cc99'
        - '#ddbb88'
        - '#66bb88'
        - '#bb9955'
        - '#bbaa55'
        - '#66aa99'
        - '#559988'
        - '#bbaa66'
        - '#bb9966'
        - '#ffeebb'
        - '#77bb99'
        - '#eeccaa'
        - '#eeddaa'
        - '#ddcc99'
        - '#66aa88'
        - '#bbbb77'
        - '#77bb88'
        - '#669999'
        - '#aaaa66'
        - '#aa9966'
        - '#99aa66'
        - '#99ccbb'
        - '#88bbaa'
        - '#77aa99'
        - '#ffeecc'
        - '#ffffcc'
        - '#669988'
        - '#eeddbb'
        - '#aaddbb'
        - '#eeffcc'
        - '#99ccaa'
        - '#cceebb'
        - '#88bb99'
        - '#77aa88'
        - '#aaaa77'
        - '#aa9977'
        - '#99cc99'
        - '#99aa77'
        - '#999966'
        - '#88aa77'
        - '#77aa77'
        - '#99bbbb'
        - '#ddffee'
        - '#cceedd'
        - '#bbddcc'
        - '#aaccbb'
        - '#ffeedd'
        - '#ffffdd'
        - '#99bbaa'
        - '#eeeecc'
        - '#eeffdd'
        - '#ddddbb'
        - '#88aa99'
        - '#ddeecc'
        - '#ddffdd'
        - '#779988'
        - '#ccddbb'
        - '#cceecc'
        - '#bbddbb'
        - '#aaccaa'
        - '#999977'
        - '#99aa88'
        - '#99bb99'
        - '#889977'
        - '#88aa88'
        - '#eeffff'
        - '#ddeeee'
        - '#ccdddd'
        - '#ffffee'
        - '#ffeeee'
        - '#eeeedd'
        - '#eeffee'
        - '#ddeedd'
        - '#ccddcc'
        - '#bbccbb'
        - '#aabbaa'
        - '#99aa99'
        - '#ffffff'
        - '#eeeeee'
    mostGroupedColors:
        - '#66bb99'
bottomLine:
    averageColor: '#66bb99'
    lightestColor: '#66bb99'
    darkestColor: '#55bb99'
    minmaxWhite:
        - '#66bb99'
        - '#55bb99'
    minmaxRed:
        - '#66aa99'
        - '#55bb99'
    minmaxGreen:
        - '#55bb99'
        - '#66aa99'
    minmaxBlue:
        - '#66aa99'
        - '#66bb99'
    mostFrequentColors:
        - '#66aa99'
    mostSatulightedColors:
        - '#55bb99'
        - '#66bb99'
        - '#66aa99'
    mostGroupedColors:
        - '#66bb99'
