version: colorful-192x108-16bit-v13palette
palette:
    - note: Most frequent color
      value: '#66ccbb'
      count: 17263
    - note: Most distant color from primary color
      value: '#000000'
averageColor: '#6dccb8'
lightestColor: '#ffffff'
darkestColor: '#66aa55'
mostFrequentColors:
    - value: '#66ccbb'
      count: 17775
    - value: '#ffffff'
      count: 88
mostSatulightedColors:
    - value: '#55ccbb'
      count: 9
    - value: '#66bb77'
      count: 2
    - value: '#77bb55'
      count: 3
mostGroupedColors:
    - value: '#66ccbb'
      count: 17773
bottomHalf:
    averageColor: '#6ccbb8'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    mostFrequentColors:
        - value: '#66ccbb'
          count: 17263
        - value: '#ffffff'
          count: 103
    mostSatulightedColors:
        - value: '#55ccbb'
          count: 1
        - value: '#cceeaa'
          count: 1
    mostGroupedColors:
        - value: '#66ccbb'
          count: 17263
bottomThird:
    averageColor: '#66caba'
    lightestColor: '#ffffff'
    darkestColor: '#66aa55'
    mostFrequentColors:
        - value: '#66ccbb'
          count: 18781
        - value: '#ffffff'
          count: 50
    mostSatulightedColors:
        - value: '#66cccc'
          count: 1
        - value: '#559977'
          count: 4
        - value: '#77aa55'
          count: 154
    mostGroupedColors:
        - value: '#66ccbb'
          count: 18781
bottomLine:
    averageColor: '#66ccbb'
    lightestColor: '#77ccbb'
    darkestColor: '#66ccbb'
    mostFrequentColors:
        - value: '#66ccbb'
          count: 20628
    mostSatulightedColors:
        - value: '#66ccbb'
          count: 20628
    mostGroupedColors:
        - value: '#66ccbb'
          count: 20520
