version: 10
palette:
    - '#446644'
    - '#ffffff'
averageColor: '#e1e4d2'
lightestColor: '#ffffff'
darkestColor: '#224422'
mostFrequentColors:
    - '#eeeedd'
    - '#446644'
mostSatulightedColors:
    - '#cceebb'
    - '#669977'
mostGroupedColors:
    - '#eeeedd'
bottomHalf:
    averageColor: '#e0e3d1'
    lightestColor: '#ffffff'
    darkestColor: '#224422'
    mostFrequentColors:
        - '#eeeedd'
        - '#446644'
    mostSatulightedColors:
        - '#88bb88'
        - '#ddffee'
        - '#eeffdd'
    mostGroupedColors:
        - '#eeeedd'
bottomThird:
    averageColor: '#e9ead9'
    lightestColor: '#ffffff'
    darkestColor: '#224422'
    mostFrequentColors:
        - '#eeeedd'
        - '#446644'
    mostSatulightedColors:
        - '#558866'
        - '#557744'
    mostGroupedColors:
        - '#eeeedd'
bottomLine:
    averageColor: '#eeeedd'
    lightestColor: '#eeeedd'
    darkestColor: '#eeeedd'
    mostFrequentColors:
        - '#eeeedd'
    mostSatulightedColors:
        - '#eeeedd'
    mostGroupedColors:
        - '#eeeedd'
